config/routes.rb
VotaPrato::Application.routes.draw do
  devise_for :users

  resources :comentarios

  resources :qualificacoes

  resources :clientes

  root :to => 'home#index'

  match ':controller(/:action(/:id(.:format)))'
  match 'rack',
  :to => proc{|env| [200, {"Content-Type" => "text/html"},
    ["App Rack numa rota Rails"]]}
end

app/models/cliente.rb
#coding:utf-8
class Cliente < ActiveRecord::Base
  attr_accessible :nome, :idade
  validates_presence_of :nome, message: " - deve ser preenchido"
validates_uniqueness_of :nome, message: " - nome já cadastrado"
validates_numericality_of :idade, greater_than: 0,
less_than: 100,
:message =>" - deve ser um número entre 0 e 100"
has_many :qualificacoes
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_filter :authenticate_user!, :except=> [:index, :show]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.json
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente salvo com Sucesso.' }
        format.json { render json: @cliente, status: :created, location: @cliente }
      else
        format.html { render action: "new" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.json
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :idade %><br />
    <%= f.number_field :idade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<body>
	<body>
	<html lang="en">
<head>
    <title>Clientes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
  </head>
<body>
<div class="bg-top">

<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li ><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li class="current" align="center"><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
        <section id="content"><div class=></div>
    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div><font family="Purisa" size="3px" >
</font>

		<table border="1" width="1000" align="center" color="#000" class="titulo">
				<td colspan="6" align="center"><h2 align="center"><font face="Purisa" >
Editar Clientes </h2>

<%= render 'form' %></font></td></table>

<%= link_to 'Mostrar', @cliente %> |
<%= link_to 'Voltar', clientes_path %>

app/views/clientes/index.html.erb
<html lang="en">
<head>
    <title>Clientes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
  </head>
<body>
<div class="bg-top">
  
<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li  align="center"><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li class="current"><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
<section id="content"><div class="ic"></div>
       <div class="block-1">
        <div class="border-right">
            <div class="block-1-title">
                <span>01.</span>
                <div class="text-1">Melhor<strong> Cozinha</strong></div>
                <strong class="clear"></strong>
            </div>
            <p class="border-1">Em nosso site é possível cadastrar os resturante, comída típica do mesmo, saber a nota de cada um dada pelo próprio cliente e muito mais</p>
            <a href="#" class="link-1">leia mais</a>
        </div>
        <div class="border-right">
            <div class="block-1-title">
                <span>02.</span>
                <div class="text-1">Melhor para<strong>o Cliente</strong></div>
                <strong class="clear"></strong>
            </div>
            <p class="border-1">Cadastre os clientes e tenha um controle melhor dos cadastros,veja também as críticas do cliente para com os restaurantes </p>
            <a href="#" class="link-1">leia mais</a>
        </div>
        <div class="border-right">
            <div class="block-1-title">
                <span>03.</span>
                <div class="text-3">Controle dos<strong>dados</strong></div>
                <strong class="clear"></strong>
            </div>
            <p class="border-1"> Tenha acesso aos dados do cliente, restaurante que o mesmo utilizou os serviços, a nota que o cliente deu ao estabelecimento e valor total gasto</p>
            <a href="#" class="link-1">leia mais</a>
        </div>
        <div class="block-1-last">
            <div class="block-1-title">
                <span>04.</span>
                <div class="text-4">Visão<strong>ampla</strong></div>
                <strong class="clear"></strong>
            </div>
          <p class="border-1">Tenha uma visão sistemática de todos os restaurantes e seus pratos  cadastrados com a página de comentários destinada aos clientes</p>
            <a href="#" class="link-1">leia mais</a>
        </div>
       </div>


    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div>
            
<table border=1 align="center" width="948">
  <div align="center">
                <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2 >Listagem de Clientes</div></h2></font></td>
                <tr><br>
  <tr>
        <td class="t" width="125">Nome</td>
        <td class="t" width="125">Idade</td>
        <td class="t" width="200">Controle dos cadastros</td>
  </tr>
</table>

<table>
<% @clientes.each do |cliente| %>
  <tr>
    <td width="280" ><font size="3px" color="#000"><%= cliente.nome %></td>
    <td width="270" ><font size="3px" color="#000"><%= cliente.idade %></td>
    <td width="79" ><font size="3px" color="#000"><%= link_to 'Mostrar', cliente %></td>
    <td width="79" ><font size="3px" color="#000"><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
  </tr>
<% end %>
</table>
<br><br><br>
  <%= link_to 'Novo Cliente', new_cliente_path %>

        <div class="clear"></div>
        <div class="block-3">
          <div class="h3">
            <h3 class="h3-line-2">Most delicious:</h3><br><br>
            </div>
            <div class="box-3">
              <div width="100%" align="center" cellpadding="6">
                
                  <div class="img-border"><img src="https://lh5.googleusercontent.com/-s49qRm7OunY/UO2mgJlaqYI/AAAAAAAAAFo/pX9HYJPUp-w/s182/page1-img2.jpg" alt=""></div>

                <div class="img-border"><img src="https://lh3.googleusercontent.com/-5wuT-xqNWVY/UO2mgB9A8nI/AAAAAAAAAFs/mwVZ0ZRkunI/s182/page1-img3.jpg" alt=""></div>
                
            
                  <div class="img-border"><img src="https://lh6.googleusercontent.com/-Vsb1dX6Gdqg/UO2mgleBDaI/AAAAAAAAAFw/j84mglJYLtM/s182/page1-img4.jpg" alt=""></div>
                
               
              
                  <div class="img-border"><img src="https://lh5.googleusercontent.com/-SF8N_XZFHOk/UO2mhM5iC3I/AAAAAAAAAF0/yNRVEfwLr40/s182/page1-img5.jpg" alt=""></div>
                    </div>
             
           
        </div>
       </div>
    </section> 

        </div>
</div>     
</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  

app/views/clientes/new.html.erb
<html lang="en">
<head>
    <title>Clientes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
  </head>
<body>
<div class="bg-top">

<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li  class="current" align="center"><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
        <section id="content"><div class=></div>
    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div>
            
<table border="1" align="center" width="100%">
    <div align="center">
         <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2> Novo Cliente</div></h2></font></td><br>
<%= render 'form' %>

<%= link_to 'Voltar', clientes_path %></td></table>

</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  

app/views/clientes/show.html.erb
<body>
	<html lang="en">
<head>
    <title>Restaurantes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
  </head>
<body>
<div class="bg-top">

<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li  class="current" align="center"><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
        <section id="content"><div class=></div>
    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div><font family="Purisa" size="3px" >
	
</font>


<table border="1" align="center" width="948">
    <div align="center">
         <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2 >Exibindo de Clientes</div></h2></font></td><br>
<div align="center">
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Idade:</b>
  <%= @cliente.idade %>
</p></div>
</td></table><br><br>


<%= link_to "Nova qualificação", :controller => "qualificacoes", :action => "new", :cliente => @cliente %> 
</td></table>
<div align="right"> <%= link_to 'Editar', edit_cliente_path(@cliente) %> 
<%= link_to 'Voltar', clientes_path %></div>
</div>     
</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  