config/routes.rb
VotaPrato::Application.routes.draw do
  devise_for :users

  resources :comentarios

  resources :qualificacoes

  resources :clientes

  root :to => 'home#index'

  match ':controller(/:action(/:id(.:format)))'
  match 'rack',
  :to => proc{|env| [200, {"Content-Type" => "text/html"},
    ["App Rack numa rota Rails"]]}
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  attr_accessible :comentavel_id, :comentavel_type, :conteudo
  belongs_to :comentavel, polymorphic: true
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  
   before_filter :authenticate_user!, :except=> [:index, :show]# GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comentarios }
    end
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/new
  # GET /comentarios/new.json
  def new
    @comentario = Comentario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comentario }
    end
  end

  # GET /comentarios/1/edit
  def edit
    @comentario = Comentario.find(params[:id])
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(params[:comentario])

    respond_to do |format|
      @comentario.save
        
        #format.xml { render :xml => @comentario, :status => :created, :location => @comentario }

        #format.js
      #else
       # format.html { render action: "new" }
        #format.json { render json: @comentario.errors, status: :unprocessable_entity }
        format.html{redirect_to @comentario, notice: 'Comentario salvo com Sucesso.'}
        format.xml{ render :xml => @comentario, :status => :created, :location => @comentario}
        format.js
    end
  end

  # PUT /comentarios/1
  # PUT /comentarios/1.json
  def update
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy

    respond_to do |format|
      format.html{redirect_to @comentario, notice: 'Comentario deletado.'}
      format.xml { head :ok}
      format.js { head :ok}
    end
  end
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/views/comentarios/_comentario.html.erb
<p id="comentario_<%= comentario.id %>">
<%= comentario.conteudo %> 

<%= link_to '(remover)', comentario, :method => :delete, :remote => true, :id => "remove_comentario_#{comentario.id}" %>
</p>
<%= content_for :js do %>
$('#remove_comentario_<%=comentario.id %>').bind('ajax:success', function(xhr, result){
$('#comentario_<%=comentario.id%>').remove();
}
);
<% end %>

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conteudo %><br />
    <%= f.text_area :conteudo %>
  </div>
  <div class="field">
    <%= f.label :comentavel_id %><br />
    <%= f.number_field :comentavel_id %>
  </div>
  <div class="field">
    <%= f.label :comentavel_type %><br />
    <%= f.text_field :comentavel_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/_novo_comentario.html.erb
<div id='novo_comentario'>
	<a href="#" onclick="$('#novo_comentario').children().toggle();"> Novo comentario
	</a>
	<div id="form_comentario" style="display: none;">
		<%= form_for Comentario.new, :remote => true do |f| %>
		<%= hidden_field :comentario, :comentavel_id, :value => comentavel.id %>
		<%= hidden_field :comentario, :comentavel_type, :value => comentavel.class %>

		<div class="field">
			<%= f.label 'conteudo' %> <br/>
			<%= f.text_area 'conteudo' %>
		</div>
		<div class="actions">
			<%= f.submit %>
			<a href="#" onclick="$('#novo_comentario').children().toggle();">
				Cancelar

			</a>
		</div>
		<% end %>
	</div>
</div>
<%content_for :js do%>
	$('#form_comentario').bind('ajax:complete', function(xhr, result){
	$('#comentarios').html(result.responseText);
	$('#form_comentario textarea').val("")
	$('#form_comentario').hide();
	$('#novo_comentario >a').show();
});
<%end%>

app/views/comentarios/create.js.erb
<%= render(:partial => "comentarios/comentario", :collection => @comentario.comentavel.comentarios) %>

app/views/comentarios/edit.html.erb
<html lang="en">
<head>
    <title>Clientes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
  </head>
<body>
<div class="bg-top">

<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li  class="current" align="center"><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
        <section id="content"><div class=></div>
    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div>
            
<table border="1" align="center" width="100%">
    <div align="center">
         <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2> Editando Comentario</div></h2></font></td><br>

<div align="center"><%= render 'form' %></div>
<div align="right"><%= link_to 'Mostrar', @comentario %> 
<%= link_to 'Voltar', comentarios_path %></div></font></td></table>
</div>     
</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  

app/views/comentarios/index.html.erb
<html lang="en">
<head>
    <title>Clientes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
  </head>
<body>
<div class="bg-top">
  
<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li  align="center"><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li class="current"><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
<section id="content"><div class="ic"></div>
       <div class="block-1">
        <div class="border-right">
            <div class="block-1-title">
                <span>01.</span>
                <div class="text-1">Melhor<strong> Cozinha</strong></div>
                <strong class="clear"></strong>
            </div>
            <p class="border-1">Em nosso site é possível cadastrar os resturante, comída típica do mesmo, saber a nota de cada um dada pelo próprio cliente e muito mais</p>
            <a href="#" class="link-1">leia mais</a>
        </div>
        <div class="border-right">
            <div class="block-1-title">
                <span>02.</span>
                <div class="text-1">Melhor para<strong>o Cliente</strong></div>
                <strong class="clear"></strong>
            </div>
            <p class="border-1">Cadastre os clientes e tenha um controle melhor dos cadastros,veja também as críticas do cliente para com os restaurantes </p>
            <a href="#" class="link-1">leia mais</a>
        </div>
        <div class="border-right">
            <div class="block-1-title">
                <span>03.</span>
                <div class="text-3">Controle dos<strong>dados</strong></div>
                <strong class="clear"></strong>
            </div>
            <p class="border-1"> Tenha acesso aos dados do cliente, restaurante que o mesmo utilizou os serviços, a nota que o cliente deu ao estabelecimento e valor total gasto</p>
            <a href="#" class="link-1">leia mais</a>
        </div>
        <div class="block-1-last">
            <div class="block-1-title">
                <span>04.</span>
                <div class="text-4">Visão<strong>ampla</strong></div>
                <strong class="clear"></strong>
            </div>
          <p class="border-1">Tenha uma visão sistemática de todos os restaurantes e seus pratos  cadastrados com a página de comentários destinada aos clientes</p>
            <a href="#" class="link-1">leia mais</a>
        </div>
       </div>


    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div>
            
<table border=1 align="center" width="948">
  <div align="center">
                <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2 >Listagem de Comentarios</div></h2></font></td>
                <tr><br>

  <tr>
    <td class="t" width="125">Conteudo</font></th>
    <td class="t" width="125">Comentavel</font></th>
    <td class="t" width="200">Comentavel type</font> </th>
  
  </tr>
</table>
<table>
<% @comentarios.each do |comentario| %>
  <tr>
    <td width="280" height="70  "><font size="3px" color="#000"><%= comentario.conteudo %></td>


    <td width="270" ><font size="3px" color="#000"><%= comentario.comentavel_id %></td>
   
       

   <td width="79" ><font size="3px" color="#000"><%= link_to 'Mostrar', comentario %></td>
   <td width="79" ><font size="3px" color="#000"><%= link_to 'Editar', edit_comentario_path(comentario) %></td>
    <td width="79" ><font size="3px" color="#000"><%= link_to 'Delete', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>


<%= link_to 'Novo comentário', new_comentario_path %>


      <div class="clear"></div>
        <div class="block-3">
          <div class="h3">
            <h3 class="h3-line-2">Most delicious:</h3><br><br>
            </div>
            <div class="box-3">
              <div width="100%" align="center" cellpadding="6">
                
                  <div class="img-border"><img src="https://lh5.googleusercontent.com/-s49qRm7OunY/UO2mgJlaqYI/AAAAAAAAAFo/pX9HYJPUp-w/s182/page1-img2.jpg" alt=""></div>

                <div class="img-border"><img src="https://lh3.googleusercontent.com/-5wuT-xqNWVY/UO2mgB9A8nI/AAAAAAAAAFs/mwVZ0ZRkunI/s182/page1-img3.jpg" alt=""></div>
                
            
                  <div class="img-border"><img src="https://lh6.googleusercontent.com/-Vsb1dX6Gdqg/UO2mgleBDaI/AAAAAAAAAFw/j84mglJYLtM/s182/page1-img4.jpg" alt=""></div>
                
               
              
                  <div class="img-border"><img src="https://lh5.googleusercontent.com/-SF8N_XZFHOk/UO2mhM5iC3I/AAAAAAAAAF0/yNRVEfwLr40/s182/page1-img5.jpg" alt=""></div>
                    </div>
             
           
        </div>
       </div>
    </section> 


</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  

app/views/comentarios/new.html.erb
<html lang="en">
<head>
    <title>Clientes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
  </head>
<body>
<div class="bg-top">

<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li  class="current" align="center"><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
        <section id="content"><div class=></div>
    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div>
            
<table border="1" align="center" width="100%">
    <div align="center">
         <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2> Novo Cliente</div></h2></font></td><br>

<div align="center"><%= render 'form' %></div>
</td></table>
<div align="right"><%= link_to 'Voltar', comentarios_path %></div>
</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  

app/views/comentarios/show.html.erb
<html lang="en">
<head>
    <title>Clientes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
  </head>
<body>
<div class="bg-top">
  
<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li class="current" align="center"><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
        <section id="content"><div class=></div>
    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div>
            
<table  align="center" width="100%" border="1">
                <div align="center">
                <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2 >Exibindo Comentários</div></h2></font></td>
                <tr><br>

<div align="center"><p id="notice"><%= notice %></p>

<p>
  <b>Conteudo:</b>
  <%= @comentario.conteudo %>
</p>

<p>
  <b>Comentavel:</b>
  <%= @comentario.comentavel_id %>
</p>

<p>
  <b>Comentavel type:</b>
  <%= @comentario.comentavel_type %><br>
</p></div>
</font></td></table>

<div align="right">
<%= link_to 'Edit', edit_comentario_path(@comentario) %> 
<%= link_to 'Voltar', comentarios_path %></div>



</div>     
</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  