config/routes.rb
VotaPrato::Application.routes.draw do
  devise_for :users

  resources :comentarios

  resources :qualificacoes

  resources :clientes

  root :to => 'home#index'

  match ':controller(/:action(/:id(.:format)))'
  match 'rack',
  :to => proc{|env| [200, {"Content-Type" => "text/html"},
    ["App Rack numa rota Rails"]]}
end

app/controllers/qualificacoes_controller.rb
class QualificacoesController < ApplicationController
   before_filter :authenticate_user!, :except=> [:index, :show]
  # GET /qualificacoes
  # GET /qualificacoes.json
  def index
    @qualificacoes = Qualificacao.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @qualificacoes }
    end
  end

  # GET /qualificacoes/1
  # GET /qualificacoes/1.json
  def show
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @qualificacao }
    end
  end

  # GET /qualificacoes/new
  # GET /qualificacoes/new.json
  def new    
    @qualificacao = Qualificacao.new
    if  params[:cliente]
      @qualificacao.cliente = Cliente.find(params[:cliente])
    end
    if params[:restaurante]
      @qualificacao.restaurante = Restaurante.find(params[:restaurante])
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @qualificacao }
    end
  end

  # GET /qualificacoes/1/edit
  def edit
    @qualificacao = Qualificacao.find(params[:id])
  end

  # POST /qualificacoes
  # POST /qualificacoes.json
  def create
    @qualificacao = Qualificacao.new(params[:qualificacao])

    respond_to do |format|
      if @qualificacao.save
        format.html { redirect_to @qualificacao, notice: 'Qualificacao salvo com Sucesso.' }
        format.json { render json: @qualificacao, status: :created, location: @qualificacao }
      else
        format.html { render action: "new" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /qualificacoes/1
  # PUT /qualificacoes/1.json
  def update
    @qualificacao = Qualificacao.find(params[:id])

    respond_to do |format|
      if @qualificacao.update_attributes(params[:qualificacao])
        format.html { redirect_to @qualificacao, notice: 'Qualificacao was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @qualificacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qualificacoes/1
  # DELETE /qualificacoes/1.json
  def destroy
    @qualificacao = Qualificacao.find(params[:id])
    @qualificacao.destroy

    respond_to do |format|
      format.html { redirect_to qualificacoes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/qualificacoes_helper.rb
module QualificacoesHelper
end

app/views/qualificacoes/_form.html.erb
<%= form_for(@qualificacao) do |f| %>
  <% if @qualificacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@qualificacao.errors.count, "error") %> prohibited this qualificacao from being saved:</h2>

      <ul>
      <% @qualificacao.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.label :cliente_id %><br />
      <%= f.collection_select(:cliente_id, Cliente.order('nome'), :id, :nome, {:prompt => true}) %>
      
  </div>
  <div class="field">
    <%= f.label :restaurante_id %><br />
      <%= f.collection_select( :restaurante_id, Restaurante.order('nome'), :id, :nome, {:prompt => true}) %>

  </div>
  <div class="field">
    <%= f.label :nota %><br />
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :valor_gasto %><br />
    <%= f.text_field :valor_gasto %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<br>
<br>
<br>
<br>
<br>
<br>

app/views/qualificacoes/edit.html.erb
<html lang="en">
<head>
    <title>Clientes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
  </head>
<body>
<div class="bg-top">

<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li class="current" align="center"><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
        <section id="content"><div class=></div>
    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div>
            

<table border="1" align="center" width="100%">
    <div align="center">
         <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2 >Editando Qualificações</div></h2></font></td><br>

<div align="center"><%= render 'form' %></div>
</font></td></table>
<div align="right">
<%= link_to 'Mostrar', @qualificacao %> 
<%= link_to 'Voltar', qualificacoes_path %></div>


</div>     
</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  

app/views/qualificacoes/index.html.erb
<html lang="en">
<head>
    <title>Restaurantes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
    <link href='http://fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
  </head>
<body>
<div class="bg-top">

<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li ><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li class="current" align="center"><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
<section id="content"><div class="ic"></div>
       <div class="block-1">
        <div class="border-right">
            <div class="block-1-title">
                <span>01.</span>
                <div class="text-1">Melhor<strong> Cozinha</strong></div>
                <strong class="clear"></strong>
            </div>
            <p class="border-1">Em nosso site é possível cadastrar os resturante, comída típica do mesmo, saber a nota de cada um dada pelo próprio cliente e muito mais</p>
            <a href="#" class="link-1">leia mais</a>
        </div>
        <div class="border-right">
            <div class="block-1-title">
                <span>02.</span>
                <div class="text-1">Melhor para<strong>o Cliente</strong></div>
                <strong class="clear"></strong>
            </div>
            <p class="border-1">Cadastre os clientes e tenha um controle melhor dos cadastros,veja também as críticas do cliente para com os restaurantes </p>
            <a href="#" class="link-1">leia mais</a>
        </div>
        <div class="border-right">
            <div class="block-1-title">
                <span>03.</span>
                <div class="text-3">Controle dos<strong>dados</strong></div>
                <strong class="clear"></strong>
            </div>
            <p class="border-1"> Tenha acesso aos dados do cliente, restaurante que o mesmo utilizou os serviços, a nota que o cliente deu ao estabelecimento e valor total gasto</p>
            <a href="#" class="link-1">leia mais</a>
        </div>
        <div class="block-1-last">
            <div class="block-1-title">
                <span>04.</span>
                <div class="text-4">Visão<strong>ampla</strong></div>
                <strong class="clear"></strong>
            </div>
          <p class="border-1">Tenha uma visão sistemática de todos os restaurantes e seus pratos  cadastrados com a página de comentários destinada aos clientes</p>
            <a href="#" class="link-1">leia mais</a>
        </div>
       </div>

    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div>
            
            
<table border="1" align="center" width="948">
    <div align="center">
         <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2 >Listagem de Qualificações</div></h2></font></td><br>

        <td class="t" width="150">Nome cliente</td>
        <td class="t" width="150">Restaurante</td>
        <td class="t" width="150">valor gasto</td>
        <td class="t" width="150">Nota</td>
        <td class="t" width="250">Controle de cadastros</td>
  </tr>
</table>
<table>
<% @qualificacoes.each do |qualificacao| %>
  <tr>
    <td width="189"><%= qualificacao.cliente.nome %></td>
    <td width="189"><%= qualificacao.restaurante.nome %></td>
    <td width="189"><%= qualificacao.nota %></td>
    <td width="189"><%= qualificacao.valor_gasto %></td>
    <td width="63"><%= link_to 'Mostrar', qualificacao %></td>
    <td width="63"><%= link_to 'Editar', edit_qualificacao_path(qualificacao) %></td>
    <td width="63"><%= link_to 'Remover',qualificacao, method: :delete, data: { confirm: 'Você tem certeza?'}%></td> 
   
    
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Nova Qualificacao', new_qualificacao_path %>


      <div class="clear"></div>
        <div class="block-3">
          <div class="h3">
            <h3 class="h3-line-2">Most delicious:</h3><br><br>
            </div>
            <div class="box-3">
              <div width="100%" align="center" cellpadding="6">
                
                  <div class="img-border"><img src="https://lh5.googleusercontent.com/-s49qRm7OunY/UO2mgJlaqYI/AAAAAAAAAFo/pX9HYJPUp-w/s182/page1-img2.jpg" alt=""></div>

                <div class="img-border"><img src="https://lh3.googleusercontent.com/-5wuT-xqNWVY/UO2mgB9A8nI/AAAAAAAAAFs/mwVZ0ZRkunI/s182/page1-img3.jpg" alt=""></div>
                
            
                  <div class="img-border"><img src="https://lh6.googleusercontent.com/-Vsb1dX6Gdqg/UO2mgleBDaI/AAAAAAAAAFw/j84mglJYLtM/s182/page1-img4.jpg" alt=""></div>
                
               
              
                  <div class="img-border"><img src="https://lh5.googleusercontent.com/-SF8N_XZFHOk/UO2mhM5iC3I/AAAAAAAAAF0/yNRVEfwLr40/s182/page1-img5.jpg" alt=""></div>
                    </div>
             
           
        </div>
       </div>
    </section> 




</div>     
</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  

app/views/qualificacoes/new.html.erb
<html lang="en">
<head>
    <title>Clientes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
  </head>
<body>
<div class="bg-top">

<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li  class="current" align="center"><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
        <section id="content"><div class=></div>
    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div>
            

<table border="1" align="center" width="100%">
    <div align="center">
         <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2 >Nova Qualificações</div></h2></font></td><br>

<%= render 'form' %>
</td></table>
<div align="right">
<%= link_to 'Voltar', qualificacoes_path %></div>
</div>     
</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  

app/views/qualificacoes/show.html.erb
<html lang="en">
<head>
    <title>Clientes</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" media="screen" href="css/reset.css">
    <link rel="stylesheet" type="text/css" media="screen" href="css/style.css">
  </head>
<body>
<div class="bg-top">

<div id="user_nav" align= "center">
  <% if user_signed_in? %>
    Entrou como <%= current_user.email %>. Não é você?
    <%= link_to "Sair", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Casdastrar-se", new_user_registration_path %> ou <%= link_to "Entrar", new_user_session_path %>
  <% end %>
</div>
<div class="bgr">
    <header>
      <h1><a href="file:///C:/Users/Emidio/Desktop/Home/home.html"><img src="https://lh6.googleusercontent.com/-uW7BA4WRbJ8/UO2meYp5j2I/AAAAAAAAAFY/yVGTQIVj5_Y/s350/logo.jpg" alt=""></a></h1>
        <nav>  
            <ul class="menu">
              <li><a href="http://localhost:3000/home">Home</a></li>
              <li><a href="http://localhost:3000/restaurantes">Restaurantes</a></li>
              <li><a href="http://localhost:3000/clientes">Clientes</a></li>
              <li class="current" align="center"><a href="http://localhost:3000/qualificacoes">Qualificacoes</a></li>
              <li><a href="http://localhost:3000/comentarios">Comentarios</a></li>
            </ul>
         </nav>
    </header>
        <section id="content"><div class=></div>
    <div class="block-2 pad-1">
        <div class="box-2 top-2"></div>
            
<table  align="center" width="100%" border="1">
                <div align="center">
                <font face="Purisa" class="h3-line top-1"  class="h2-line"><h2 >Exibindo de Qualificações</div></h2></font></td>
                <tr><br>
<div align="center"><% unless @qualificacao.comentarios.empty?%>
<%= comentarios @qualificacao %>
<% end %>
<%= novo_comentario(@qualificacao)%> </div><br>

<div align="center"><p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <%= @qualificacao.cliente.nome %>
</p>

<p>
  <b>Restaurante:</b>
  <%= @qualificacao.restaurante.nome%>
</p>

<p>
  <b>Nota:</b>
  <%= @qualificacao.nota %>
</p>

<p>
  <b>Valor gasto:</b>
  <%= valor_formatado(@qualificacao.valor_gasto) %>
</p></div>
</font></td></table>
<div align="right">
<%= link_to 'Editar', edit_qualificacao_path(@qualificacao) %> 
<%= link_to 'Voltar', qualificacoes_path %></div>




</div>     
</div>
  <footer>
      <p>Desenvolvido por: Renato Emidio e Victor Marques<br>© 2013 RubyThree.</p> 
  </footer>     
</body>
</html>  